name: Build Debian Image (amd64)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install debootstrap
        run: sudo apt-get update && sudo apt-get install -y debootstrap

      - name: Create build directory
        run: mkdir -p build/bookworm

      - name: Download and install Debian base system
        run: |
          sudo debootstrap bookworm build/bookworm

      - name: Enter chroot environment
        run: |
          sudo chroot build/bookworm/ /bin/bash -c "
            apt-get update
            apt-get install -y locales locales-all python3 openssh-server ifupdown2
            apt-get -y autoremove --purge ifupdown
            apt-get clean
            rm -rf /etc/ssh/ssh_host*
            rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
            find /var/log -type f -exec truncate -s 0 {} \;
            truncate -s 0 /etc/hostname
            truncate -s 0 /etc/machine-id
            truncate -s 0 /var/lib/dbus/machine-id
            exit
          "

      - name: Create archive
        run: |
          sudo tar -cvzf debian-12-standard_$(cat build/bookworm/etc/debian_version)-1_amd64.tar.zst -C build/bookworm .
          echo "DEBIAN_VERSION=$(cat build/bookworm/etc/debian_version)" >> $GITHUB_ENV

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: debian-12-standard_${{ env.DEBIAN_VERSION }}-1_amd64.tar.zst
          asset_name: debian-12-standard_${{ env.DEBIAN_VERSION }}-1_amd64.tar.zst
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
